### ISSUE TITLE
安装依赖

### ISSUE THREAD

**Issue by Hunlongyu** [JasKang/tsrv#2]
![image](https://user-images.githubusercontent.com/15273630/103325186-96709b00-4a85-11eb-8b45-85aa4c916787.png)

```
yarn install tsrv -D // 无法安装 tsrv, 且报错.
```
```
yarn add tsrv -D  // 可以成功安装
```

**Comment by jaskang** [comment]
yarn 没有提供 yarn install moduleName 这种命令哦

文档 -> https://yarnpkg.com/cli

**Comment by Hunlongyu** [comment]
哈哈, 作者在线啊. 
我能问一下这个怎么用啊, 是我理解的 用来创建 vue3 组件库的吗?
我用 vite 初始化一个库, 安装这个依赖. 无法启动. 
用 vue/cli 也失败.
必须空的库吗? npm init ?

**Comment by Hunlongyu** [comment]
rollup 没有用过呢? 哈哈 有什么教程嘛?

**Comment by jaskang** [comment]
这是用来打包组件的

**Comment by Hunlongyu** [comment]
哈哈, 原谅我白痴了
我想知道这个 tsrv 依赖, 应该怎么正确使用呀.
如果太麻烦了, 就算了
我自己再琢磨琢磨吧.

**Comment by jaskang** [comment]
> 我想知道这个 tsrv 依赖, 应该怎么正确使用呀.

😢 等有时间会补充文档。
